config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'welcome/index'
  get 'sessions/new'
  get 'users/new'

  resources :feedbacks, only: %w[new create]

  resources :tests, only: :index do
    post :start, on: :member
  end

  # GET /test_passages/38/result
  resources :test_passages, only: %w[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :my_badges, only: :index

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true, except: [:index]
      end
    end
    resources :gists, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges, dependent: :destroy

  enum rule: %i[by_level by_category by_attempt]

  validates :name, :rule, :rule_value, presence: true
  validates :rule_value, numericality: { only_integer: true }, if: :by_level?
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    @badge.image = @badge.rule + '.png'

    if @badge.save
      redirect_to [:admin, @badge], notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge], notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_url, notice: t('.success')
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :description, :rule, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.name %></td>
  <td class="align-middle"><%= badge.description %></td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= badge.rule_value %></td>
  <td class="align-middle"><%= link_to t('links.show'), admin_badge_path(badge) %></td>
  <td class="align-middle">
    <%= link_to t('links.edit'),
                edit_admin_badge_path(badge) %>
  </td>
  <td class="align-middle">
    <%= link_to t('links.delete'),
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('links.delete_confirmation') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, @badge], local: true) do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label t('.name') %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label t('.description') %><br>
    <%= form.text_area :description, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label t('.rule') %><br>
    <%= form.select :rule, Badge.rules.keys, prompt: true %>
  </p>

  <p>
    <%= form.label t('.rule_value'), class: 'rule_value_label' %><br>
    <%= form.text_field :rule_value, placeholder: t('.placeholder.rule_value'), class: 'rule_value_field' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header')%></h1>
<%= render 'form' %>

<%= link_to t('links.back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header')%></h1>
<p>
  <%= link_to t('links.new_badge'), new_admin_badge_path %>
</p>

<% if @badges.present? %>
<table class="table">
    <tr>
      <th scope="col"><%= t('.name')%></th>
      <th scope="col"><%= t('.description')%></th>
      <th scope="col"><%= t('.rule')%></th>
      <th scope="col"><%= t('.rule_value')%></th>
      <th colspan="3"><%= t('.action')%></th>
    </tr>
    <%= render @badges %>
<% else %>
  <p><%= t('.empty_badge_list')%></p>
<% end %>
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.header')%></h1>

<%= render 'form' %>

<%= link_to t('links.back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%= t('.name')%>:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong><%= t('.description')%>:</strong>
  <%= @badge.description %>
</p>

<p>
  <strong><%= t('.rule')%>:</strong>
  <%= @badge.rule %>
</p>

<p>
  <strong><%= t('.rule_value')%>:</strong>
  <%= @badge.rule_value %>
</p>

<%= link_to t('links.edit'), edit_admin_badge_path(@badge) %> |
<%= link_to t('links.back'), admin_badges_path %>