config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  get 'welcome/index'
  get 'sessions/new'
  get 'users/new'

  resources :feedbacks, only: %w[new create]

  resources :tests, only: :index do
    post :start, on: :member
  end

  # GET /test_passages/38/result
  resources :test_passages, only: %w[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index
  resources :my_badges, only: :index

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true, except: [:index]
      end
    end
    resources :gists, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_set_question

  scope :by_date, ->(date) { where('updated_at > ?', date) }
  scope :success, -> { where(passed: true) }

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def completed?
    current_question.nil?
  end

  def passed?
    result_percent >= 85
  end

  def expired?
    return false if test.timer.nil?
    expiration_date < Time.current
  end

  def timeleft
    (expiration_date - Time.current).to_i
  end

  def update_passed
    self.passed = passed?

    save!
  end

  def result_percent
    (correct_questions.to_f / questions_count) * 100
  end

  def questions_count
    test.questions.count
  end

  def current_question_number
    test.questions.order(:id).index(current_question).next
  end

  def current_passage_percent
    100 * current_question_number.to_f / questions_count
  end

  private

  def expiration_date
    created_at + test.timer.minutes
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_save_set_question
    self.current_question = if new_record?
                              test.questions.first
                            elsif expired?
                              nil
                            else
                              next_question unless completed?
                            end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update

    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      @test_passage.update_passed
      TestsMailer.completed_test(@test_passage).deliver_now
      badges = give_badges
      redirect_to result_test_passage_path(@test_passage)
      flash[:notice] = t('.new_badges_html', url: my_badges_url) if badges.any?
      flash[:alert] = t('.time_is_over') if @test_passage.expired?
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    service.call

    if service.success?
      @gist = Gist.create!(url: service.responce[:html_url], question: @test_passage.current_question, author: @test_passage.user)

      redirect_to @test_passage, notice: t('.success_html', url: @gist.url)
    else
      redirect_to @test_passage, notice: t('.failure')
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def give_badges
    new_badges = SelectNewBadgesByRuleService.new(@test_passage).call
    current_user.badges << new_badges
    new_badges
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<% if  @test_passage.passed? %>
      <h2><%= t('.passed_header') %></h2>
      <p><%= t('.result_message') %>
        <span class="passed"><%= @test_passage.result_percent %>%</span></p>
<% else %>
    <h2><%= t('.failed_header') %></h2>
    <p><%= t('.result_message') %>
      <span class="failed"><%= @test_passage.result_percent %>%</span></p>
<% end %>

<%= link_to t('links.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title ) %></h1>
<div class="progress">
  <%= content_tag :div, t('.progress_bar', percent: @test_passage.current_passage_percent.to_i),
                  class: 'progress-bar progress-bar-info',
                  role: 'progressbar',
                  data: { percent: @test_passage.current_passage_percent} %>
</div>
<% if @test_passage.test.timer %>
<div class="timer">
  Remaining Time: <%= content_tag :span, '',
                  class: 'countdown',
                  data: { seconds: @test_passage.timeleft } %>
</div>
<% end %>
<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
        <p>
          <%= b.check_box id: "answer_ids_#{b.object_id}" %>
          <%= b.label %>
        </p>
    <% end %>

    <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
    <p><%= form.submit t('links.next') %></p>
<% end %>